name: Cron Crawling

on:
  schedule:
    # every thursday 6:30
    - cron: '30 6 * * 4'

jobs:
  cron:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["16"]
    name: Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: functions

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'data'
          author_name: Billboard Crawler
          author_email: coderhyun476@gmail.com
          message: 'Billboard Hot 100 crawling at ${{ steps.date.outputs.date }}'

